steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/', 'workspace/']

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/PROJECT_ID/IMAGE_NAME:TAG']

  # SSH into the VM and run the Docker container
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh USERNAME@INSTANCE_NAME --zone ZONE --command "docker run -d -p HOST_PORT:CONTAINER_PORT asia-south1-docker.pkg.dev/PROJECT_ID/IMAGE_NAME:TAG"

images:
  - 'asia-south1-docker.pkg.dev/PROJECT_ID/IMAGE_NAME:TAG'
