# steps:
#   - name: 'gcr.io/cloud-builders/gcloud'
#     args:  ['sudo bash pull.sh']
    
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'instance-1'  # Replace with your VM instance name
      - '--zone=asia-south1-a'
      - '--command'
      - 'cd /var/www/html && ./pull.sh'
